// storage key
export const PORTKEY_OFF_RAMP_GUARDIANS_APPROVE_LIST = 'PORTKEY_OFF_RAMP_GUARDIANS_APPROVE_LIST';

export const PORTKEY_SIGN_IN_STORAGE_KEY = 'PORTKEY_SIGN_IN_STORAGE_KEY';

export const PORTKEY_SIGN_UP_STORAGE_KEY = 'PORTKEY_SIGN_IN_STORAGE_KEY';

export const PORTKEY_LOGIN_STORAGE_KEY = 'PORTKEY_LOGIN_STORAGE_KEY';

export const PORTKEY_SIGN_IN_STORAGE_KEY_TELEGRAM = PORTKEY_SIGN_IN_STORAGE_KEY + '_TELEGRAM';

export const PORTKEY_SIGN_UP_STORAGE_KEY_TELEGRAM = PORTKEY_SIGN_UP_STORAGE_KEY + '_TELEGRAM';
