import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './index.css';
import PortkeyProvider from '@/provider/Portkey';
import Script from 'next/script';
import '@portkey/did-ui-react/dist/assets/index.css';
import WebWalletProvider from '@/provider/WebWalletProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script src="https://telegram.org/js/telegram-web-app.js" />
        <WebWalletProvider>
          <PortkeyProvider>{children}</PortkeyProvider>
        </WebWalletProvider>
      </body>
    </html>
  );
}
